services:
  node-service:
    container_name: bull-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - prod.env
    restart: unless-stopped
